- import_tasks: chrony_file.yaml
- import_tasks: sysctl_file.yaml
- import_tasks: repo_file.yaml
- import_tasks: chronyd_service.yaml
- import_tasks: sysctl_p.yaml
- import_tasks: yum_nova.yaml
- import_tasks: yum_sysfsutils.yaml
- import_tasks: nova_file.yaml
- import_tasks: libvirtd_file.yaml
- import_tasks: nova_start.yaml
- import_tasks: libvirtd_start.yaml
- import_tasks: kvm.yaml
- import_tasks: ceph_dir.yaml
- import_tasks: ceph_file.yaml
- import_tasks: secret_file.yaml
- import_tasks: secret.yaml
- import_tasks: create_user_nova.yaml
- import_tasks: nova_auth_file.yaml
- import_tasks: chmod_nova.yaml
- import_tasks: yum_ceilometer.yaml
- import_tasks: ceilometer_conf.yaml
